name: geoana-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.22.4
  - scipy>=1.8
  - libdlf

  # optionals
  - matplotlib
  - utm

  # documentation
  - sphinx
  - pydata-sphinx-theme==0.15.4
  - sphinx-gallery>=0.1.13
  - numpydoc>=1.5
  - jupyter
  - graphviz
  - pillow

  # testing
  - pytest
  - pytest-cov

  # Building
  - pip
  - meson-python>=0.15.0
  - meson
  - ninja
  - cython>=3.0.8
  - setuptools_scm
  - python-build