name: Testing With Conda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: geoana-test
        create-args: >-
          python=${{ matrix.python-version }}
          numpy>=2.0.0rc1
          scipy>=1.8
          libdlf
          cython>=3.0.8
          setuptools_scm
          meson-python>=0.15.0
          build
          discretize
          matplotlib
          jupyter
          utm
          pytest
          pytest-cov
          sphinx
          sphinx-gallery>=0.1.13
          pydata-sphinx-theme=0.13.3
          numpydoc>=1.5
          graphviz
          pillow
          numba
        cache-environment: true
    - name: Install Our Package
      run: |
        pip install --no-build-isolation --editable . --config-settings=setup-args="-Dwith_extensions=true"
        conda list
    - name: Run Tests
      run: |
        pytest --cov-config=.coveragerc --cov=geoana --cov-report=xml -s -v -W ignore::DeprecationWarning
    - name: "Upload coverage to Codecov"
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
