name: Testing With Conda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        environment-file: .github/environment_ci.yml
        activate-environment: geoana-test
        python-version: ${{ matrix.python-version }}

    - name: Conda information
      run: |
        conda info
        conda list
        conda config --show

    - name: Install Our Package
      run: |
        pip install . --config-settings=setup-args="-Dwith_extensions=true"

    - name: Run Tests
      run: |
        pytest --cov-config=.coveragerc --cov=geoana --cov-report=xml -s -v -W ignore::DeprecationWarning

    - name: "Upload coverage to Codecov"
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
